#!/usr/bin/env python3
"""Generates the distribution packages a release publishes elsewhere.

The release workflow builds an sdist + wheel and attaches them to the
GitHub release with SHA256 checksums. This script then generates the
pieces that live OUTSIDE this repository — today, a Homebrew formula —
pointed at the release asset, so `brew install` and the engine share one
source of bytes: the tagged, checksummed sdist. Nothing here runs on a
user's machine; it runs in CI (and by hand for testing) at release time.

The formula installs into its own virtualenv with a pinned PyYAML
resource, whose URL and digest are read live from PyPI's JSON API and
written into the formula: Homebrew forbids network access during
`install`, so every dependency must be declared as a pinned resource,
and a hand-copied hash is exactly the kind of quiet wrong this repo
has been burned by before.

Usage (what the workflow does):
    python3 release_packages.py \
        --version 2.2.0 \
        --asset-url https://github.com/OWNER/REPO/releases/download/v2.2.0/nexgen_engine-2.2.0.tar.gz \
        --asset-sha256 <sha256 of that sdist> \
        --out-dir /tmp/tap/Formula
"""
from __future__ import annotations

import argparse
import json
import urllib.request

HOMEPAGE = "https://github.com/matteopasseri407/NeXgen-Engine"
LICENSE = "PolyForm-Noncommercial-1.0.0"
PY_YAML_VERSION = "6.0.2"

FORMULA_TEMPLATE = '''# Generated by 03-INFRA/scripts/release_packages.py at release time.
# Do not edit by hand: every release rewrites this file. The url is the
# release sdist asset, whose sha256 is verified before install.
class NexgenEngine < Formula
  desc "One Git repo to configure every AI coding CLI (AGENTS.md, MCP, skills, memory)"
  homepage "{homepage}"
  url "{asset_url}"
  sha256 "{asset_sha256}"
  license "{license}"
  version "{version}"

  # Invariant from the engine's pyproject: PyYAML is the only runtime
  # dependency, so the formula carries exactly one resource, pinned.
  depends_on "python@3.12"

  resource "pyyaml" do
    url "{pyyaml_url}"
    sha256 "{pyyaml_sha256}"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/nexgen --version")
  end
end
'''


def _pyyaml_pinned() -> tuple[str, str]:
    """The PyYAML sdist URL and sha256, as PyPI states them right now."""
    url = f"https://pypi.org/pypi/PyYAML/{PY_YAML_VERSION}/json"
    with urllib.request.urlopen(url, timeout=30) as resp:
        data = json.load(resp)
    for entry in data["urls"]:
        if entry.get("packagetype") == "sdist":
            return entry["url"], entry["digests"]["sha256"]
    raise SystemExit(f"PyPI lists no sdist for PyYAML {PY_YAML_VERSION}")


def generate_formula(*, version: str, asset_url: str, asset_sha256: str) -> str:
    pyyaml_url, pyyaml_sha256 = _pyyaml_pinned()
    return FORMULA_TEMPLATE.format(
        homepage=HOMEPAGE,
        asset_url=asset_url,
        asset_sha256=asset_sha256,
        license=LICENSE,
        version=version,
        pyyaml_url=pyyaml_url,
        pyyaml_sha256=pyyaml_sha256,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the release's external packages (Homebrew formula)")
    parser.add_argument("--version", required=True, help="Engine version (without the v prefix)")
    parser.add_argument("--asset-url", required=True, help="Public URL of the release sdist")
    parser.add_argument("--asset-sha256", required=True, help="sha256 of the release sdist")
    parser.add_argument("--out-dir", required=True, help="Directory to write the formula into")
    args = parser.parse_args(argv)

    if not args.asset_sha256:
        raise SystemExit("refusing to generate a formula without a sha256: an unverifiable url is worse than none")

    from pathlib import Path

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    formula = out / "nexgen.rb"
    formula.write_text(generate_formula(
        version=args.version,
        asset_url=args.asset_url,
        asset_sha256=args.asset_sha256,
    ), encoding="utf-8")
    print(f"formula written: {formula}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
