"""Installing what a module declares, using primitives the engine already owns.

``modules.py`` is inventory and judgment; this is the hands. The split is the
same one the rest of the layer keeps, and it is why hosting a new kind of
module is a vocabulary change rather than a new execution path: a module names
shims, units and runtime integrations, and the engine renders them with the
same idempotent machinery it uses for itself.

Nothing here runs code supplied by a module, and nothing installs itself: only
a module the machine has declared ``local`` in ``modules.state.yaml`` is ever
touched. That is what makes it safe for the guard cycle to call this every
round -- a deleted shim or a disabled unit is quietly repaired, instead of the
module and the guard overwriting each other forever.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path

from nexgen_core.modules import ModuleDef, ModuleState
from nexgen_core.paths import resolve_home
from nexgen_core.scheduler import HOST_MUTATIONS_DISABLED_ENV

SHIM_MARKER = "Generated by NeXgen Engine for module '{module}'"
_POSIX_SHIM = """#!/usr/bin/env bash
# """ + SHIM_MARKER + """. Edits are overwritten.
exec "{target}" "$@"
"""
_WINDOWS_SHIM = """@echo off
REM """ + SHIM_MARKER + """. Edits are overwritten.
"{target}" %*
"""

IS_WINDOWS = sys.platform == "win32"


def shim_template() -> str:
    return _WINDOWS_SHIM if IS_WINDOWS else _POSIX_SHIM


def shim_path(bin_dir: Path, name: str) -> Path:
    """Launchers carry .cmd on Windows, or the shell will not find them."""
    return bin_dir / (f"{name}.cmd" if IS_WINDOWS else name)


# Requirement kinds that make INSTALLING impossible, as opposed to those that
# only decide whether the module can RUN right now. Free VRAM, group
# membership and device permissions belong to the second group: a shim and a
# unit file are correct to write even while the GPU is busy or the user has
# not logged back in yet. Conflating the two would make installation depend on
# the weather.
BLOCKS_INSTALL = ("source", "binary")


@dataclass(frozen=True)
class Unmet:
    """One requirement a module declared and the machine does not satisfy."""

    kind: str
    detail: str

    @property
    def blocks_install(self) -> bool:
        return self.kind in BLOCKS_INSTALL

    def __str__(self) -> str:
        return f"{self.kind}: {self.detail}"


def _host_mutations_disabled() -> bool:
    return os.environ.get(HOST_MUTATIONS_DISABLED_ENV, "").strip().lower() in {"1", "true", "yes", "on"}


def _free_gpu_mb() -> int | None:
    """Free VRAM on the first GPU, or None when it cannot be determined."""
    nvidia_smi = shutil.which("nvidia-smi")
    if not nvidia_smi:
        return None
    try:
        proc = subprocess.run(
            [nvidia_smi, "--query-gpu=memory.free", "--format=csv,noheader,nounits"],
            capture_output=True, text=True, timeout=10, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if proc.returncode != 0:
        return None
    first = proc.stdout.strip().splitlines()
    try:
        return int(first[0].strip()) if first else None
    except ValueError:
        return None


def _module_is_running(module: ModuleDef, home: Path | None = None) -> bool:
    """True when any unit this module provides is active right now."""
    if not module.provides.systemd_units:
        return False
    systemctl = shutil.which("systemctl")
    if not systemctl:
        return False
    names = [Path(rel).name for rel in module.provides.systemd_units]
    result = _run([systemctl, "--user", "is-active", *names])
    if result is None:
        return False
    return any(line.strip() == "active" for line in result.stdout.splitlines())


def check_requirements(module: ModuleDef, home: Path | None = None) -> list[Unmet]:
    """What the module asked for and did not get. Empty means ready.

    Reported rather than enforced: a module whose GPU is busy right now is not
    broken, and a machine that cannot answer about its GPU at all must not be
    told its module is fine either.
    """
    home_units = home  # only used to ask systemd whether the module is already up
    unmet: list[Unmet] = []

    for binary in module.requires.binaries:
        if not shutil.which(binary):
            unmet.append(Unmet("binary", f"{binary} not found on PATH"))

    for device in module.requires.devices:
        path = Path(os.path.expanduser(device))
        if not path.exists():
            unmet.append(Unmet("device", f"{device} does not exist"))
        elif not os.access(path, os.R_OK):
            unmet.append(Unmet("device", f"{device} is not readable"))

    if module.requires.groups:
        # The groups of THIS process, not of the user record: a fresh usermod
        # does not apply until the session is restarted, and reporting the
        # record would call a module ready while it still cannot open its
        # devices.
        try:
            import grp

            member_of = {grp.getgrgid(gid).gr_name for gid in os.getgroups()}
        except (ImportError, KeyError, OSError):
            member_of = set()
        for group in module.requires.groups:
            if group not in member_of:
                unmet.append(Unmet(
                    "group",
                    f"this session is not in group '{group}' "
                    f"(sudo usermod -aG {group} $USER, then log out and back in)",
                ))

    for raw in module.requires.paths:
        if not Path(os.path.expanduser(raw)).exists():
            unmet.append(Unmet("path", f"{raw} does not exist"))

    if module.requires.gpu_mb and not _module_is_running(module, home_units):
        # Skipped while the module's own units are up: its memory is exactly
        # what makes the GPU look full, and reporting "not runnable" about
        # something that is running is the kind of true-but-useless message
        # that makes a diagnostic worth ignoring.
        free = _free_gpu_mb()
        if free is None:
            unmet.append(Unmet("gpu", f"needs {module.requires.gpu_mb} MB but free VRAM cannot be determined"))
        elif free < module.requires.gpu_mb:
            unmet.append(Unmet("gpu", f"needs {module.requires.gpu_mb} MB, {free} MB free"))

    if module.source_path is not None and not module.source_path.is_dir():
        unmet.append(Unmet("source", f"{module.source} is not a directory"))

    return unmet


def run_health_check(module: ModuleDef, timeout: int = 60) -> tuple[bool | None, str]:
    """Ask the module to prove it works. (None, reason) when it cannot say.

    Called by the doctor, never by the guard: running module-supplied code on a
    timer is exactly what the declaration model exists to avoid.
    """
    if not module.health:
        return None, "no health command declared"
    cwd = module.source_path
    if cwd is not None and not cwd.is_dir():
        return None, f"source {cwd} does not exist"
    try:
        proc = subprocess.run(
            module.health, shell=True, cwd=str(cwd) if cwd else None,
            capture_output=True, text=True, timeout=timeout, check=False,
        )
    except subprocess.TimeoutExpired:
        return False, f"health command timed out after {timeout}s"
    except (OSError, subprocess.SubprocessError) as exc:
        return None, f"health command could not run: {exc}"
    if proc.returncode == 0:
        return True, _health_detail(proc.stdout, "healthy")
    return False, _health_detail(
        f"{proc.stdout}\n{proc.stderr}", f"exit {proc.returncode}"
    )


# What a health command says about a failure, in the order we would rather hear
# it. Taking the last line instead hands back whatever the module logged last,
# which is usually a startup notice and never the reason.
_FAILURE_MARKERS = ("[FAIL]", "FAIL:", "ERROR", "Error:", "error:", "Traceback")


def _health_detail(output: str, fallback: str) -> str:
    lines = [line.strip() for line in (output or "").splitlines() if line.strip()]
    if not lines:
        return fallback
    for marker in _FAILURE_MARKERS:
        hits = [line for line in lines if marker in line]
        if hits:
            return hits[0][:200]
    return lines[-1][:200]


def _write_if_different(path: Path, content: str, dry_run: bool) -> bool:
    """True when it wrote. Idempotence is what lets the guard call this often."""
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    if dry_run:
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp-{os.getpid()}")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)
    return True


def install_shims(module: ModuleDef, home: Path, dry_run: bool = False) -> list[str]:
    """Expose the module's commands in ~/.local/bin, as launchers not symlinks.

    A launcher can be regenerated over a stale symlink left by an older install
    -- which is exactly how a command ends up silently pointing at a previous
    version of the module.
    """
    actions: list[str] = []
    bin_dir = home / ".local" / "bin"
    for name, raw_target in module.provides.shims:
        target = Path(os.path.expanduser(raw_target))
        launcher = shim_path(bin_dir, name)
        if not target.exists():
            actions.append(f"{module.id}: shim '{name}' skipped, target {target} does not exist")
            continue
        content = shim_template().format(module=module.id, target=target)
        if launcher.is_symlink() and not dry_run:
            launcher.unlink()
        if _write_if_different(launcher, content, dry_run):
            if not dry_run and not IS_WINDOWS:
                launcher.chmod(0o755)
            actions.append(f"{module.id}: shim '{name}' -> {target}")
    return actions


def install_config_files(module: ModuleDef, home: Path, dry_run: bool = False) -> list[str]:
    """Drop the small user-level files a module needs in specific places."""
    actions: list[str] = []
    if not module.provides.config_files:
        return actions
    source = module.source_path
    if source is None:
        actions.append(f"{module.id}: declares config files but no 'source' to read them from")
        return actions
    for rel, raw_dest in module.provides.config_files:
        src = source / rel
        if not src.is_file():
            actions.append(f"{module.id}: config file {rel} missing from {source}")
            continue
        dest = Path(os.path.expanduser(raw_dest)).expanduser()
        if dest.is_dir():
            dest = dest / src.name
        # Refuse anything outside the user's own tree: a module must not be
        # able to write into /etc from a timer.
        try:
            dest.resolve().relative_to(home.resolve())
        except ValueError:
            actions.append(f"{module.id}: refused {dest}, outside {home}")
            continue
        if _write_if_different(dest, src.read_text(encoding="utf-8"), dry_run):
            actions.append(f"{module.id}: config {dest} installed")
    return actions


def install_compose_file(module: ModuleDef, engine_root: Path | None, dry_run: bool = False) -> list[str]:
    """Deploy a stack the module ships, under the engine's deploy root."""
    actions: list[str] = []
    if not module.provides.compose_file:
        return actions
    if engine_root is None or not module.stack:
        actions.append(f"{module.id}: ships a compose file but declares no 'stack' to deploy it as")
        return actions
    source = module.source_path
    if source is None:
        actions.append(f"{module.id}: ships a compose file but has no 'source' to read it from")
        return actions
    src = source / module.provides.compose_file
    if not src.is_file():
        actions.append(f"{module.id}: compose file {module.provides.compose_file} missing from {source}")
        return actions
    from nexgen_core.stack.services import deploy_root

    dest = deploy_root(engine_root) / module.stack / "docker-compose.yml"
    if _write_if_different(dest, src.read_text(encoding="utf-8"), dry_run):
        actions.append(f"{module.id}: stack '{module.stack}' deployed to {dest}")
    return actions


def install_systemd_units(
    module: ModuleDef,
    home: Path,
    dry_run: bool = False,
    log: Callable[[str], None] = lambda _msg: None,
) -> list[str]:
    """Copy and enable the module's user units, without touching the engine's.

    Returns only what CHANGED. A note about the platform is reported through
    ``log``: keeping it among the actions would make every guard cycle look
    like a modification, and idempotence would be a claim rather than a fact.
    """
    actions: list[str] = []
    if not module.provides.systemd_units:
        return actions
    if not sys.platform.startswith("linux"):
        # Saying nothing here would leave the module looking installed on a
        # platform where half of it cannot exist.
        log(
            f"{module.id}: {len(module.provides.systemd_units)} systemd unit(s) declared, "
            f"but this is {sys.platform}: they were not installed"
        )
        return actions
    source = module.source_path
    if source is None:
        actions.append(f"{module.id}: declares systemd units but no 'source' to read them from")
        return actions

    unit_dir = home / ".config" / "systemd" / "user"
    changed: list[str] = []
    for rel in module.provides.systemd_units:
        src = source / rel
        if not src.is_file():
            actions.append(f"{module.id}: unit {rel} missing from {source}")
            continue
        dst = unit_dir / src.name
        if _write_if_different(dst, src.read_text(encoding="utf-8"), dry_run):
            changed.append(src.name)
            actions.append(f"{module.id}: unit {src.name} installed")

    if not changed or dry_run or _host_mutations_disabled():
        return actions
    systemctl = shutil.which("systemctl")
    if not systemctl:
        actions.append(f"{module.id}: systemctl not found; units written but not enabled")
        return actions
    _run([systemctl, "--user", "daemon-reload"])
    # Enabled, not started: bringing a module up is the user's move, and a
    # unit that needs a GPU must not race the machine's own startup.
    result = _run([systemctl, "--user", "enable", *changed])
    if result is not None and result.returncode != 0:
        actions.append(f"{module.id}: enabling units failed: {(result.stderr or result.stdout).strip()}")
    return actions


def _run(args: Sequence[str], timeout: int = 30) -> subprocess.CompletedProcess | None:
    try:
        return subprocess.run(args, capture_output=True, text=True, timeout=timeout, check=False)
    except (OSError, subprocess.SubprocessError):
        return None


def install_module(
    module: ModuleDef,
    *,
    home: Path | None = None,
    engine_root: Path | None = None,
    dry_run: bool = False,
    log: Callable[[str], None] = lambda _msg: None,
) -> list[str]:
    """Render everything the module declares. Returns what changed."""
    home_dir = resolve_home(home)
    actions = install_shims(module, home_dir, dry_run)
    actions += install_config_files(module, home_dir, dry_run)
    actions += install_compose_file(module, engine_root, dry_run)
    actions += install_systemd_units(module, home_dir, dry_run, log)
    # runtime_hooks are deliberately not rendered here: the guard cycle already
    # owns CLI integration through runtimes/, and two writers on the same
    # settings file is the failure this whole change exists to remove. The
    # declaration is what lets the doctor say whether the hook is in place.
    for action in actions:
        log(action)
    return actions


def uninstall_module(
    module: ModuleDef,
    *,
    home: Path | None = None,
    dry_run: bool = False,
    log: Callable[[str], None] = lambda _msg: None,
) -> list[str]:
    """Take back what the module installed. Returns what changed.

    Only files the engine generated are removed: a launcher is recognised by
    the marker it was written with, so a command the user put there by hand
    with the same name is left alone. Declaring a module absent has to mean
    something, or 'remove a module' is a promise the engine does not keep.
    """
    home_dir = resolve_home(home)
    actions: list[str] = []

    for name, _target in module.provides.shims:
        launcher = shim_path(home_dir / ".local" / "bin", name)
        if not launcher.is_file():
            continue
        try:
            body = launcher.read_text(encoding="utf-8")
        except OSError:
            continue
        if SHIM_MARKER.format(module=module.id) not in body:
            actions.append(f"{module.id}: left '{name}' alone, it was not generated for this module")
            continue
        if not dry_run:
            launcher.unlink()
        actions.append(f"{module.id}: shim '{name}' removed")

    units = [Path(rel).name for rel in module.provides.systemd_units]
    present = [u for u in units if (home_dir / ".config" / "systemd" / "user" / u).is_file()]
    if present and not dry_run and not _host_mutations_disabled():
        systemctl = shutil.which("systemctl")
        if systemctl:
            # Stopped as well as disabled: a unit left running after its module
            # was removed is the kind of orphan nobody thinks to look for.
            _run([systemctl, "--user", "disable", "--now", *present])
    for unit in present:
        path = home_dir / ".config" / "systemd" / "user" / unit
        if not dry_run:
            path.unlink(missing_ok=True)
        actions.append(f"{module.id}: unit {unit} removed")
    if present and not dry_run and not _host_mutations_disabled():
        systemctl = shutil.which("systemctl")
        if systemctl:
            _run([systemctl, "--user", "daemon-reload"])

    for action in actions:
        log(action)
    return actions


def install_declared_modules(
    states: Sequence[ModuleState],
    *,
    home: Path | None = None,
    engine_root: Path | None = None,
    dry_run: bool = False,
    log: Callable[[str], None] = lambda _msg: None,
) -> list[str]:
    """Install every module this machine declared local. Safe to call on a timer."""
    actions: list[str] = []
    for state in states:
        if not state.module.provides:
            continue
        if state.state != "local":
            # Absent has to mean removed, or the engine keeps maintaining
            # commands and units for something the machine has switched off.
            actions += uninstall_module(state.module, home=home, dry_run=dry_run, log=log)
            continue
        unmet = check_requirements(state.module, home)
        blocking = [u for u in unmet if u.blocks_install]
        if blocking:
            log(f"{state.module.id}: not installed, {'; '.join(str(u) for u in blocking)}")
            continue
        for pending in unmet:
            # Installed, but it will not work until this is fixed. Saying so is
            # the difference between "not ready yet" and "silently broken".
            log(f"{state.module.id}: installed, but not runnable yet - {pending}")
        if any(u.kind == "path" for u in unmet) and state.module.requires.setup:
            # The engine installs; it does not provision. Naming the command is
            # what keeps a missing 17 GB of model weights from looking like
            # nothing at all.
            log(f"{state.module.id}: to provision it, run: {state.module.requires.setup}")
        actions += install_module(
            state.module, home=home, engine_root=engine_root, dry_run=dry_run, log=log
        )
    return actions
